image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: |
      cd $HOME/emsdk && source ./emsdk_env.sh && cd /workspace/web/library/distributions/JavaScript && GSL_INCLUDE_DIRS=$HOME/usr/include GSL_LIBRARY=$HOME/usr/lib/libgsl.a GSL_CBLAS_LIBRARY=$HOME/usr/lib/libgslcblas.a  ./compile_to_js.sh
      cp /workspace/web/library/distributions/JavaScript/output/libat.js /workspace/web/src/
      cp /workspace/web/library/distributions/JavaScript/output/libat.js /workspace/web/src/static/js
      cp /workspace/web/library/distributions/JavaScript/output/libat.wasm /workspace/web/src/
      cp /workspace/web/library/distributions/JavaScript/output/libat.wasm /workspace/web/src/static/js
      npm install
#    command: npm run start
