ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: |
      git clone https://github.com/emscripten-core/emsdk.git
      cd emsdk && ./emsdk install latest && ./emsdk activate latest
      wget -q "http://ftpmirror.gnu.org/gnu/gsl/gsl-latest.tar.gz"
      mkdir $HOME/gsl-latest
      tar -xzf gsl-latest.tar.gz -C $HOME/gsl-latest
      mv $HOME/gsl-latest/** $HOME/gsl-latest/gsl
      mkdir $HOME/usr
      cd /workspace/web/emsdk && source ./emsdk_env.sh && cd $HOME/gsl-latest/gsl/ && emconfigure ./configure --prefix=$HOME/usr --disable-shared && emmake make -j2 && emmake make install
      cp $HOME/usr/lib/libgsl.a library/distributions/JavaScript/
      cp $HOME/usr/lib/libgslcblas.a library/distributions/JavaScript/
#      cd /workspace/web/emsdk && source ./emsdk_env.sh && cd /workspace/web/library/distributions/JavaScript && GSL_INCLUDE_DIRS=$HOME/usr/include GSL_LIBRARY=$HOME/usr/lib/libgsl.a GSL_CBLAS_LIBRARY=$HOME/usr/lib/libgslcblas.a  ./compile_to_js.sh
#      npm install
#    command: npm run start